### DISCUSSION TITLE
Manual package compatibility result reporting

### DISCUSSION THREAD

**Discussion by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1507] [Ideas]
There are many reasons that our build system could fail for reasons that are hard to fix either by the package author or by us. One came up today, but I'm sure more already lurk undiscovered in the index.

The compatibility matrix is so prominent on the package page that it puts those packages at a disadvantage, so I wanted to discuss the potential for a manual compatibility statement.

If (and it's a big if) we do this, we should tie the results to package versions just as we do for the automated build results. This means that package authors will need to update their compatibility information manually with every release. However, giving them that task means it's more likely that results (if they exist) will be current.

I don't think we should allow compatibility for a branch, only the latest tagged beta and stable versions. We should also put a note close to the compatibility matrix indicating it's manually set rather than automated.

I can see a new key in the `.spi.yml` file that could work for this:

```yaml
compatibility:
  - version: '1.0.0-beta1'
    platforms: ['ios', 'macos', 'linux']
    swift_versions: ['5.6', '5.5', '5.4']
  - version: '1.0.0'
    platforms: ['ios', 'macos', 'linux']
    swift_versions: ['5.6', '5.5', '5.4']
  - version: '0.9.5'
    platforms: ['ios', 'macos', 'linux']
    swift_versions: ['5.6', '5.5', '5.4']
```

Naturally, this will never be as good as automatic results, but it's better than no results. Or is it? That's the discussion 😂
