### DISCUSSION TITLE
Use SPI config ordering for Documentation

### DISCUSSION THREAD

**Discussion by Mordil** [SwiftPackageIndex/SwiftPackageIndex-Server#1970] [Bug]
I just added SPI support for hosting DocC documentation, and the output is not following [my specified ordering in the YAML file](https://github.com/Mordil/RediStack/blob/master/.spi.yml):

```yaml
builder:
  configs:
    - documentation_targets: ['RediStack', 'RedisTypes', 'RediStackTestUtils']
```

Instead, it sorts alphabetically, which leaves the module [**RedisTypes** as the entry point for documentation and first in the list of module documentation](https://swiftpackageindex.com/Mordil/RediStack/master/documentation/redistypes).

This causes me a problem, because **RediStack** is the main purpose of the package.
