### DISCUSSION TITLE
Dedicated compiler flag for building documentations

### DISCUSSION THREAD

**Discussion by stevapple** [SwiftPackageIndex/SwiftPackageIndex-Server#2330] [Ideas]
Vapor uses a `BUILDING_DOCC` flag with documentation building, which opts out of `@_exported import`s that are annoying in the documentation. We would like similar feature with SPI too.

Note that Vapor doesn’t use the DocC plugin. AFAIK the plugin doesn’t support such feature, but it’s rather useful.
https://github.com/vapor/api-docs/blob/e282e02bee7c7f25a61e4744c9add5f067a5af08/generate-package-api-docs.swift#L47

**Comment by finestructure** [comment]
We've very recently added support for [custom docc flags](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2303). Would that help?

You can set them via `custom_documentation_parameters` in your `.spi.yml` file. For example:

```yml
version: 1
builder:
    configs:
    - documentation_targets: [t0]
      custom_documentation_parameters: [--foo, bar]
```
