### ISSUE TITLE
Emojis in READMEs not fully formatted

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1195]
Very minor, but seems to have an easy fix.

Currently an emoji gets replaced with this `g-emoji` element like below:

```
<g-emoji class="g-emoji" alias="warning" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/26a0.png">
   ⚠️
  </g-emoji>
```

In this case it should be the full emoji like: ⚠️ 

[Source](https://swiftpackageindex.com/Sherlouk/swift-snapshot-testing-stitch)

GitHub seem to resolve this with a bit of CSS:

```css
g-emoji {
    font-family: Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
    font-style: normal !important;
    font-weight: 400;
    line-height: 1;
    vertical-align: -.075em;
}
```
(The first line there is the most important one...)
