### ISSUE TITLE
Xcode and SPM builds issues with spi.yml scheme

### ISSUE THREAD

**Issue by MortenGregersen** [SwiftPackageIndex/SwiftPackageIndex-Server#1633]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/MortenGregersen/Bagbutik

**Please explain what data is incorrect and what you expected to see**

In my package I have 2 products: "Bagbutik" (the library) and "bagbutik" (the CLI).

In the repository I have a `.spi.yml` file with the following contents:

```yaml
version: 1
builder:
  configs:
  - platform: macos-xcodebuild
    scheme: Bagbutik
  - platform: macos-xcodebuild-arm
    scheme: Bagbutik
  - platform: ios
    scheme: Bagbutik
  - platform: tvos
    scheme: Bagbutik
  - platform: watchos
    scheme: Bagbutik
```

I expect, that the builders will only build the "Bagbutik" scheme.

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

In this build, we can see that it also builds the "BagbutikCLI" target and "BagbutikGenerator" target:
- https://swiftpackageindex.com/builds/551BA916-FE7E-4F4B-BF88-E9264CA9D5E3

**Screenshots**

![CleanShot 2022-03-22 at 22 03 33](https://user-images.githubusercontent.com/759680/159575716-3eb0375d-dbf1-47aa-91be-8fdb6a7f2527.png)
