### ISSUE TITLE
Use SPI manifest `documentation_targets` sort order for documentation archives

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1974]
### Discussed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/1970

<div type='discussions-op-text'>

<sup>Originally posted by **Mordil** August 14, 2022</sup>
I just added SPI support for hosting DocC documentation, and the output is not following [my specified ordering in the YAML file](https://github.com/Mordil/RediStack/blob/master/.spi.yml):

```yaml
builder:
  configs:
    - documentation_targets: ['RediStack', 'RedisTypes', 'RediStackTestUtils']
```

Instead, it sorts alphabetically, which leaves the module [**RedisTypes** as the entry point for documentation and first in the list of module documentation](https://swiftpackageindex.com/Mordil/RediStack/master/documentation/redistypes).

This causes me a problem, because **RediStack** is the main purpose of the package.</div>
