### ISSUE TITLE
Cannot see documentation for multiple targets

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#2033]
Package: https://swiftpackageindex.com/ChimeHQ/ChimeKit

My package has two targets with docc documentation. I'm using this `.spi.yml`:

```yaml
version: 1
builder:
  configs:
    - documentation_targets: [ChimeLSPAdapter, ChimeExtensionInterface]
```

When I link the documentation link for the package, I only see docs for `ChimeLSPAdapter`. I see no listing for `ChimeExtensionInterface`. However, I can manually navigate to `https://swiftpackageindex.com/ChimeHQ/ChimeKit/main/documentation/chimeextensioninterface`.

Does the documentation hosting support viewing multiple targets like this? Is it the first one listed in `.spi.yml` that shows up at `https://swiftpackageindex.com/ChimeHQ/ChimeKit/main/documentation` ?
