### ISSUE TITLE
Enable doc generation on Linux

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2187]
I've put up a .spi.yml for both `ordo-one/package-benchmark` and `ordo-one/package-frostflake` that should try it out:

E.g.:
```
version: 1
builder:
  configs:
  - documentation_targets: [Frostflake]
    platform: linux
```

_Originally posted by @hassila in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2184#discussioncomment-4386990_
