### ISSUE TITLE
Builds timed out for Teco

### ISSUE THREAD

**Issue by stevapple** [SwiftPackageIndex/SwiftPackageIndex-Server#2224]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/teco-project/teco

**Please explain what data is incorrect and what you expected to see**

Most builds are hitting the time limit, causing the compatibility to be incorrect.

**Additional context**

Since the Teco project structures very like Soto, I believe #1845 is talking about exactly the same thing.

**Comment by finestructure** [comment]
Thanks for making us aware of the timeout issues, @stevapple .

There isn't much we can do on our end I'm afraid but looking through the package manifest with its many likely quite similar targets, I think I'd advise using the `target` (for `macos-spm` and `linux`) and `scheme` directives (for `macos-xcodebuild`, `ios`, `tvos`, `watchos`) and pick one representative target to build.

https://swiftpackageindex.com/swiftpackageindex/spimanifest/0.14.0/documentation/spimanifest/commonusecases#Control-Targets-and-Schemes

For example:

```yml
version: 1
builder:
  configs:
  - platform: macos-spm
    target: TecoAaV20200224
  - platform: linux
    target: TecoAaV20200224
  - platform: ios
    scheme: TecoAaV20200224
  - platform: macos-xcodebuild
    scheme: TecoAaV20200224
  - platform: tvos
    scheme: TecoAaV20200224
  - platform: watchos
    scheme: TecoAaV20200224
```

where I've just picked the first target `TecoAaV20200224`.

In my local testing this brought the build time down to a minute or two and should fix this issue.
