### ISSUE TITLE
The SPI Manifest validator should check the maximum size of a manifest

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2869]
From https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2867#discussion-6133921. We validate this .spi.yml fine:

```
version: 1
builder:
  configs:
  - documentation_targets:
    - GitHubRestAPIActions
    - GitHubRestAPIActivity
    - GitHubRestAPIApps
    - GitHubRestAPIBilling
    - GitHubRestAPIChecks
    - GitHubRestAPIClassroom
    - GitHubRestAPICode_Scanning
    - GitHubRestAPICodes_Of_Conduct
    - GitHubRestAPICodespaces
    - GitHubRestAPICopilot
    - GitHubRestAPIDependabot
    - GitHubRestAPIDependency_Graph
    - GitHubRestAPIDesktop
    - GitHubRestAPIEmojis
    - GitHubRestAPIGists
    - GitHubRestAPIGit
    - GitHubRestAPIGitignore
    - GitHubRestAPIInteractions
    - GitHubRestAPIIssues
    - GitHubRestAPILicenses
    - GitHubRestAPIMarkdown
    - GitHubRestAPIMerge_Queue
    - GitHubRestAPIMeta
    - GitHubRestAPIMigrations
    - GitHubRestAPIOidc
    - GitHubRestAPIOrgs
    - GitHubRestAPIPackages
    - GitHubRestAPIProjects
    - GitHubRestAPIPulls
    - GitHubRestAPIRate_Limit
    - GitHubRestAPIReactions
    - GitHubRestAPIRepos
    - GitHubRestAPISearch
    - GitHubRestAPISecret_Scanning
    - GitHubRestAPISecurity_Advisories
    - GitHubRestAPITeams
    - GitHubRestAPIUsers
```

Where in reality, it hits [this limit](https://github.com/SwiftPackageIndex/SPIManifest/blob/7396dece8cb542b98dc9cdf259b7241488a898eb/Sources/SPIManifest/Manifest.swift#L138C37-L138C42) (which was 1,000 before https://github.com/SwiftPackageIndex/SPIManifest/pull/37).

If we have a maximum limit, the validator should reject data over that size, too.
