### ISSUE TITLE
doc test google-gemini/generative-ai-swift/documentation keeps failing

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#3019]
The doc page loads fine however the test fails with a 404:

```
🎬  /google-gemini/generative-ai-swift/documentation started ...
Response:
Status:   404
Headers:  [AnyHashable("Date"): "Thu, 25 Apr 2024 10:05:10 GMT", AnyHashable("NEL"): "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", AnyHashable("Content-Type"): "text/html; charset=utf-8", AnyHashable("CF-RAY"): "879d835eba1c392e-IAD", AnyHashable("CF-Cache-Status"): "DYNAMIC", AnyHashable("Transfer-Encoding"): "chunked", AnyHashable("Server"): "cloudflare", AnyHashable("Content-Encoding"): "gzip", AnyHashable("Connection"): "keep-alive", AnyHashable("Report-To"): "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=0KyBpB3uxXfCsasEKCAJMim%2FQOvtgJLdjEGiR%2FalB9M4yDcWi2EbIaIM%2BjVYIqdX1BgkEmZ4lXmJE23M3YSkUUn7e541Bfpn1SeFI6T1RcO1C67LtUbha6vN3ZiTYLV38GGV8ND1Ow%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}"]
Data:     4780 bytes
```

This is reproducible locally.

Will disable the test for now while we investigate this false negative.

**Comment by finestructure** [comment]
Oh, I see the problem now. I'd only fixed the test name but not the URL!

```
  /google-gemini/generative-ai-swift/documentation:
    url: ${base_url}/google/generative-ai-swift/documentation
    validation:
      status: .regex((2|3)\d\d)
```
