### ISSUE TITLE
Incorrect documentation link for PassKit/Wallet

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#3601]
Logging this as I need to leave my desk for today and wanted to get it written down.

Passkit (`vapor-community/PassKit`) recently renamed to Wallet (`vapor-community/wallet`) and it's part of our documentation smoke test. I've just updated the smoke test in #3602, but it will still fail as the documentation redirect is going to the wrong place.

The documentation link on the SPI package page links to `https://swiftpackageindex.com/vapor-community/wallet/0.6.0/documentation/passkit` which is incorrect as `passkit` is presumably the name of the old target. [The `spi.yml`](https://github.com/vapor-community/wallet/blob/main/.spi.yml) has been updated and now has three new targets in it:

```yml
version: 1
builder:
  configs:
    - documentation_targets: [VaporWallet, VaporWalletPasses, VaporWalletOrders]
```

So I'm not sure why the default target hasn't updated but don't have time to look into it further today.
