### ISSUE TITLE
Cache CI build artifacts

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#391]
https://github.com/actions/cache/blob/master/examples.md#swift---swift-package-manager

**Comment by finestructure** [comment]
For the docker build we already cache the dependencies and there's no straightforward way to cache the build products themselves, because they are generated inside the build containers.

**Comment by finestructure** [comment]
Adding `.build` to the Github action workflow doesn't bring any speedup:

```
      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: .build
          key: spi-server
```

Before: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/runs/776443775?check_suite_focus=true
After: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/runs/776616928

Not going to try and debug this further for now.
