### ISSUE TITLE
Generate a production GitHub API access token

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#50]
Owned by the [organisation](https://github.com/SwiftPackageIndex), if possible.

**Comment by daveverwer** [comment]
Yea I think that's easily good enough!

It's not authenticated or anything like that, and we don't need it to be, so I can't see any downside in using that token.

**Comment by finestructure** [comment]
I created a little rester snippet to montior our prod rate limit this morning:

```
variables:
  api_url: https://api.github.com

requests:
  repos:
    url: ${api_url}/rate_limit
    headers:
      Authorization: token ${GITHUB_TOKEN}
    validation:
      status: 200
    log:
      - json.rate
```

```
❯ rester restfiles/github-rate-limit.restfile
🚀  Resting restfiles/github-rate-limit.restfile ...

🎬  repos started ...

rate: ["limit": 5000, "reset": 1590729786, "remaining": 4143]

✅  repos PASSED (0.473s)

Executed 1 test, with 0 failures
```

And that's when I realised - because I hadn't actually run any requests - that of course the rate limit is _per account_ and not _per token_.

Which makes total sense but also means that yesterday, when I burned through my rate limit testing the new activity metadata queries I _also_ shut down prod 🤪

I guess we'll need to create some sort of prod/admin account for the rate limit token.
