### ISSUE TITLE
Builder: mongo-swift-driver false negative

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#545]
The issue is that xcodebuild currently fails to pick up [`cSettings`](https://forums.swift.org/t/xcode-swiftpm-integration-ignores-csettings/38487)

The fix is to either [pass the settings explicitly](https://swiftpm.slack.com/archives/C017AA4KADQ/p1595180397031200) to `xcodebuild`:

```
xcodebuild -scheme MongoSwift GCC_PREPROCESSOR_DEFINITIONS="MONGO_SWIFT_OS_DARWIN BSON_COMPILATION MONGOC_COMPILATION”
```

or to build via `swift build`

**Comment by finestructure** [comment]
To summarise, I think our options are:

1. Somehow pass in explicit settings (via a metadata file for instance, or plain special casing of certain packages)
1. Short-circuit certain packages we know are problematic but where we agree to accept an upstream signal
1. Try `swift build` if `xcodebuild` failed
1. Wait for the Xcode build fix

**Comment by finestructure** [comment]
I think 4. could be an option if we know it’s close - i.e. in Xcode 12. However, that seems unlikely, since Xcode 12b2 is also failing.

Option 3. isn’t great, as it complicates the build further and increases run times for every failed build (which are many). We could/should limit this to macOS, which might help here. Or turn it around, run `swift build` first and then `xcodebuild`? Not sure if there are risks of false positives or if there are even gains to be expected.

**Comment by finestructure** [comment]
Re 2.: Given the [SSWG minimal requirements](https://github.com/swift-server/sswg/blob/master/process/incubation.md#minimal-requirements) for sandbox level projects and above, there’s an argument to be made to fast-path the projects from the [Swift Server Ecosystem Index](https://swift.org/server/#projects) and report them supporting latest macOS/Linux.

**Comment by daveverwer** [comment]
So, given that we're going to need a `swift build` path through the builder tool in order to support Linux builds I think the best option is to simply add another column to our build permutations table.

We currently have:

<img width="615" alt="Screenshot 2020-07-20 at 09 52 24@2x" src="https://user-images.githubusercontent.com/5180/87918797-d2331d80-ca6e-11ea-8f27-6a73ef67d0cb.png">

When we add Linux support, we will then need something like this:

<img width="765" alt="Screenshot 2020-07-20 at 09 52 36@2x" src="https://user-images.githubusercontent.com/5180/87918845-deb77600-ca6e-11ea-8890-ce81131b13bb.png">

Given that we'll already have the command structure for building packages with `swift build` at that point, I think we could justify adding one more column:

<img width="918" alt="Screenshot 2020-07-20 at 09 52 46@2x" src="https://user-images.githubusercontent.com/5180/87918911-f7279080-ca6e-11ea-88ad-116297b40d74.png">

**Comment by daveverwer** [comment]
To give an opinion on all these, I'd place them in this order from my favourite, to least favourite:

> 3. Try `swift build` if `xcodebuild` failed

Except, I wouldn't do it conditionally. Let's just run one more build for everything as I mention above.

> 1. Somehow pass in explicit settings (via a metadata file for instance, or plain special casing of certain packages)

Yep, I think this may potentially be necessary for some real edge cases that we have yet to see, but I bet they're in there somewhere.

> 2. Short-circuit certain packages we know are problematic but where we agree to accept an upstream signal

I'm happy to short circuit packages, but this does weaken the feature in that the matrix is no longer *only* showing build results, but build results and special cases.

> 4. Wait for the Xcode build fix

This could be a long time coming.

**Comment by finestructure** [comment]
Just triggered via

```
    post build macos (spm):
        url: ${base_url}/api/packages/${package}/trigger-builds
        method: POST
        headers:
            Authorization: Bearer ${builder_token}
        body:
            json:
                buildTool: spm
                platform:
                    name: macos
                    version: "x86_64"
                swiftVersion:
                    major: 5
                    minor: 2
                    patch: 4
        validation:
            status: 200
```

and all three refs are passing now:

- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/649059159
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/649059161
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/649059166

https://staging.swiftpackageindex.com/mongodb/mongo-swift-driver/builds

<img width="342" alt="Screenshot 2020-07-21 at 17 19 08" src="https://user-images.githubusercontent.com/65520/88073334-5ae8b100-cb76-11ea-87b9-f8bad23311af.png">
<img width="382" alt="Screenshot 2020-07-21 at 17 19 19" src="https://user-images.githubusercontent.com/65520/88073351-5e7c3800-cb76-11ea-8071-727fde4c9ef9.png">
