### ISSUE TITLE
Add `spm` build for macos

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#546]
Addresses #545

- [x] accept build tool parameter in trigger api (spi-server)
- [x] add build tool parameter to GL post request (spi-server)
- [x] send build tool parameter in manual trigger
- [x] check for build tool parameter in build.sh and pass to build command
- [x] add `spm` build type to builder

**Comment by finestructure** [comment]
The way this works is that it is simply up to our trigger files to trigger this additional build, i.e. the restfile needs to include one additional request per swift version:

```
    post build macos 5.2 (spm):
        url: ${base_url}/api/packages/${package}/trigger-builds
        method: POST
        headers:
            Authorization: Bearer ${builder_token}
        body:
            json:
                buildTool: spm
                platform:
                    name: macos
                    version: "x86_64"
                swiftVersion:
                    major: 5
                    minor: 2
                    patch: 4
        validation:
            status: 200
```
