### ISSUE TITLE
Add trigger command to compose file

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#598]
- [x] test prod trigger
- [x] trigger command
- [x] downscaling factor to later reduce processing rate

The way I envision this working is that now that all the pieces are in play, we add

```
  trigger-builds:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run trigger-builds --env ${ENV} --limit ${BUILD_TRIGGER_LIMIT:-1}; sleep ${BUILD_TRIGGER_SLEEP:-60}; done"
    ]
    restart: always
```

to the compose file to kick off builds.

This will trigger available builds every 60s if the gitlab queue has capacity.

The downscaling factor is a number between 0 and 1 that we set to say, 0.1 or 0.05, on staging and to 1 on prod. It scales the processing rate to 10% or 5%, meaning that staging behaves exactly like production except that processing is 10x or 20x slower (or lower capacity). We will still go through all the packages but take a lot longer.

If we need specific packages fast tracked on staging, we can use the package id based triggering mechanism via the command with a parameter to ignore downscaling (which I'll add). Or we use the existing trigger mechanism via the script and rester, which is also still available.
