### ISSUE TITLE
Better visibility into the swift version/platform validations

### ISSUE THREAD

**Issue by thomasvl** [SwiftPackageIndex/SwiftPackageIndex-Server#676]
The FAQ mentions that you use xcodebuild -list to try and pick ways to try, but some more details and/or if there is anything a package can do to help would be useful.  The detailed view for SwiftProtobuf says a few things fail, but I don't think we're aware of any fail cases, so it would be nice to understand why they appear to be failing.

**Comment by thomasvl** [comment]
Ignore this, I missed that on hover the results changed to links (was originally looking from an ipad).  That seems to have have the details.

**Comment by finestructure** [comment]
I've just had a quick look and the reason iOS (and presumably tvOS, watchOS) is failing is that we're not picking the correct scheme.

I can fix this up with an override but we're also trialling a config file that you could ship with the repo, if you'd like to give that a go: Add `.spi.yml` at the root of the package with the following content:

```
version: 1
builder:
  configs:
  - platform: ios
	scheme: SwiftProtobuf_iOS
  - platform: tvos
	scheme: SwiftProtobuf_tvOS
  - platform: watchos
	scheme: SwiftProtobuf_watchOS
```
