### ISSUE TITLE
Add `image:` to Linux in `.spi.yml`

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#686]
As discussed with Adam here:

https://swiftpm.slack.com/archives/C017AA4KADQ/p1598256932021500?thread_ts=1598047301.008200&cid=C017AA4KADQ

**Comment by finestructure** [comment]
Fix ready https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/32

This will introduce support for the following `.spi.yml` file:

```
version: 1
builder:
  configs:
  - platform: linux
    swift_version: '5.0'
    image: adamfowlerphoto/aws-sdk-swift:5.0
  - platform: linux
    swift_version: '5.1'
    image: adamfowlerphoto/aws-sdk-swift:5.1
  - platform: linux
    swift_version: '5.2'
    image: adamfowlerphoto/aws-sdk-swift:5.2
  - platform: linux
    swift_version: '5.3'
    image: adamfowlerphoto/aws-sdk-swift:5.3
```

We'll ship the above as a built in default for `https://github.com/swift-aws/aws-sdk-swift.git` for all revisions, which can be overriden by the project simply by adopting and shipping it inside the repository.

FYI @adam-fowler: We will probably roll this out later today and it would then be available for your next push to the default branch or release.
