### ISSUE TITLE
Package list nightly is failing

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#724]
https://github.com/SwiftPackageIndex/PackageList/runs/1171546031?check_suite_focus=true

Has been failing for a few days.

**Comment by Sherlouk** [comment]
Seems to be caused by our 10 second timeout but it's unclear why...

It could be because of loading the repo information ([example](https://api.github.com/repos/Kitura/Kitura-CredentialsHTTP)) or the Package.swift ([example](https://raw.githubusercontent.com/Kitura/Kitura-CredentialsHTTP/master/Package.swift)) neither of which seems entirely plausible on their own.

I thought it could be to do with how many requests we're running at once (based on how many changes are being made, it could be the script struggling to deal with a big batch) but we had that problem before and we now wait until the previous package is done before validating the next one.

Just blindly increasing the timeout and hoping it works is clearly not the right thing to do but might be interesting to see what the output is.

I also think it might be good to uncouple the validation from the nightly itself. I made the decision to do it initially to 'circumvent' GitHub's infinite cycle protection where it doesn't run GitHub actions (pull request trigger) from a merge request made by a GitHub action.

We could approach that in a couple different ways:
1. We could make it so the validation step is allowed to fail and so if the nightly passes it will always generate a new PR. We _might_ be able to update the pull request message depending on whether the validate step passed/failed. This would at least let us make a human decision and potentially validate ourselves locally or even debug this problem without waiting hours.
2. We could replace the validate step with a simple request to GitHub to trigger the action via the API. We could do this after the pull request is made. This has the downside though that by not running the validate as part of the nightly script, we may run into 'linting' violatiions (unordered etc).

You may also have other ideas about this...

**Comment by Sherlouk** [comment]
Looks like we may be able to set `continue-on-error` to true and then pick up the conclusion and use a different message.

Random example showcasing the feature:
```yml
      - name: Install dependencies
        id: composer-run
        continue-on-error: true
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        if: steps.composer-run.outcome == 'success' && steps.composer-run.conclusion == 'success'
        run: vendor/bin/phpunit
```


https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#steps-context
