### ISSUE TITLE
Validation script fails for > 1 added packages

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#847]

**Comment by finestructure** [comment]
Works fine when run locally, even without a token:

```

❯ xcrun swift validate.swift
Warning: Using anonymous authentication -- may run into rate limiting issues

+ https://github.com/guykogus/CodableGeoJSON.git
+ https://github.com/guykogus/CodableJSON.git

2 package(s) passed
```

**Comment by finestructure** [comment]
Online test passes as well: https://github.com/SwiftPackageIndex/PackageList/pull/792

My best guess is that validation fails when the nightly has exhausted the rate limit. That should also mess up runs with single additions, though.

Is it perhaps a red herring that we're observing it with multiple packages and they just happened to be submitted at times in the morning (UCT/CET) when the nightly was still in progress?

In any case, I'll look into porting over the rate limit wait/retry mechanism we're using in the nightly.

**Comment by finestructure** [comment]
Actually, the error message doesn't look like it's been a rate limit at all:

```
+ https://github.com/guykogus/CodableGeoJSON.git
+ https://github.com/guykogus/CodableJSON.git
🚨 https://github.com/guykogus/CodableJSON.git: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))
10
```

Might be a package specific problem.

**Comment by finestructure** [comment]
Cannot reproduce:

```
❯ xcrun swift validate.swift
Warning: Using anonymous authentication -- may run into rate limiting issues

+ https://github.com/guykogus/CodableGeoJSON.git
+ https://github.com/guykogus/CodableJSON.git

2 package(s) passed
```

At this point I think the best we can do is wait for another issue with an error and debug when it's happening. Specifically: check if the nightly is still running and making a `/rate_limit` call:

```yml
# rate-limit.restfile

variables:
  api_url: https://api.github.com

requests:
  repos:
    url: ${api_url}/rate_limit
    headers:
      Authorization: token ${GITHUB_TOKEN}
    validation:
      status: 200
    log:
      - json.rate
```

```
env GITHUB_TOKEN=... rester rate-limit.restfile
```
