### ISSUE TITLE
The wrong scheme from my package is being built.

### ISSUE THREAD

**Issue by Peter-Schorn** [SwiftPackageIndex/SwiftPackageIndex-Server#862]
I am trying to use the `.spi.yml` file to specify which scheme from my package is built. As shown below, I would like the `SpotifyAPI` scheme to be built for all platforms:
```
version: 1
builder:
  configs:
  - platform: watchos
    scheme: SpotifyAPI
  - platform: ios
    scheme: SpotifyAPI
  - platform: macos
    scheme: SpotifyAPI
  - platform: tvos
    scheme: SpotifyAPI
  - platform: linux
    scheme: SpotifyAPI
```
However, the `RegularExpressions-Package` scheme is being built for all platforms:
```
env DEVELOPER_DIR="/Applications/Xcode_12.2.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" build -scheme "RegularExpressions-Package" -destination "generic/platform=watchos"
```

What am I doing wrong? You can find my package on the swift package index [here](https://swiftpackageindex.com/Peter-Schorn/SpotifyAPI).
