### ISSUE TITLE
Improve spi.yml file documentation

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#864]
We need to fully document the `.spi.yml` somewhere beyond the blog post. In particular, we need to list the platform and swift version strings that we support.

**Comment by finestructure** [comment]
Where should we best publish this? The best way to document the format is probably by sharing the `Codable`s:

```swift
struct SPIManifest: Codable, Equatable {
    var version: Int = 1
    var builder: Builder

    struct Builder: Codable, Equatable {
        var configs: [BuildConfig]

        struct BuildConfig: Codable, Equatable {
            var platform: Platform?
            var swiftVersion: ShortVersion?
            var image: String?
            var scheme: String?

            enum CodingKeys: String, CodingKey {
                case platform
                case swiftVersion = "swift_version"
                case image
                case scheme
            }
        }
    }
}

enum Platform: String, Codable, ExpressibleByArgument {
    case ios
    case macosSpmArm        = "macos-spm-arm"
    case macosXcodebuildArm = "macos-xcodebuild-arm"
    case macosSpm           = "macos-spm"
    case macosXcodebuild    = "macos-xcodebuild"
    case tvos
    case watchos
    case linux
}

typealias ShortVersion = String
```

together with a couple of examples, like

```yml
version: 1
builder:
  configs:
    - platform: watchos
      scheme: Alamofire watchOS
```

and 

```yml
version: 1
builder:
  configs:
    - platform: linux
      swift_version: 5.2
      image: someone/malicious:5.2
    - platform: linux
      swift_version: 5.3
      image: swift:5.3
```
