### ISSUE TITLE
Back-end support for pulling issue and pull request data from GitHub

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#87]
This is an additional (or even multiple additional) GitHub API request to fetch:

- [x] Number of open issues
- [x] Number of open pull requests
- [x] Date of last issue being closed
- [x] Date of last pull request being closed/merged

**Comment by finestructure** [comment]
- Open issues: `open_issues_count` on `https://api.github.com/repos/{owner}/{repo}` - i.e. our existing call

**Comment by finestructure** [comment]
- Open PRs [GH API](https://developer.github.com/v3/pulls/#list-pull-requests)

where `state == open` and `draft == false`

**Comment by finestructure** [comment]
- "updated_at" from

```
requests:
  repos:
    url: ${api_url}/repos/${repo}/pulls
    query:
      state: closed
      base: master
      sort: updated
      direction: desc
    validation:
      status: 200
    log: json
```

```
🚀  Resting restfiles/github-repos-pulls.restfile ...

🎬  repos started ...

JSON: [["number": 181, "html_url": "https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/181", "author_association": "COLLABORATOR", "user": ["html_url": "https://github.com/finestructure", "avatar_url": "https://avatars0.githubusercontent.com/u/65520?v=4", ...
```

**Comment by finestructure** [comment]
Interesting: PRs are issues under the hood (that's why they share that running index - that's always puzzled me). That means we can most likely fetch both the last PR and issue closed in one go (if the page size isn't completely filled by one type - but I guess that's the kind of edge case we'd accept for a lower request count).

**Comment by finestructure** [comment]
So:

```
requests:
  repos:
    url: ${api_url}/repos/${repo}/issues
    query:
      state: closed
      sort: closed
      direction: desc
    validation:
      status: 200
    log: json
```

And look at existance of `pull_request` for most recent PR, otherwise it's an issue.

See note here: https://developer.github.com/v3/issues/#list-repository-issues
